apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "protheus.fullname" . }}-runtime
  labels:
    app.kubernetes.io/name: {{ include "protheus.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
{{- range $key, $value := .Values.runtimeConfig }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
