#!/usr/bin/env node
'use strict';
Object.defineProperty(exports, "__esModule", { value: true });
const path = require('path');
const { createDomainProxy } = require('../../lib/legacy_conduit_proxy');
const ROOT = path.resolve(__dirname, '..', '..');
const runExecutionDomain = createDomainProxy(__dirname, 'BACKLOG_AUTOSCALE', 'execution-yield-recovery');
function cleanText(v, maxLen = 260) {
    return String(v == null ? '' : v).replace(/\s+/g, ' ').trim().slice(0, maxLen);
}
function runViaRustBinary(payloadBase64) {
    const out = runExecutionDomain(['autoscale', `--payload-base64=${String(payloadBase64 || '')}`]);
    if (out && out.ok === true && out.payload && typeof out.payload === 'object') {
        return { ok: true, engine: 'conduit', payload: out.payload };
    }
    return { ok: false, engine: 'conduit', payload: out && out.payload ? out.payload : null, error: cleanText(out && out.error || 'execution_domain_failed', 260) };
}
function runViaCargo(payloadBase64) {
    return runViaRustBinary(payloadBase64);
}
function runViaRustBinaryInversion(payloadBase64) {
    const out = runExecutionDomain(['inversion', `--payload-base64=${String(payloadBase64 || '')}`]);
    if (out && out.ok === true && out.payload && typeof out.payload === 'object') {
        return { ok: true, engine: 'conduit', payload: out.payload };
    }
    return { ok: false, engine: 'conduit', payload: out && out.payload ? out.payload : null, error: cleanText(out && out.error || 'execution_domain_failed', 260) };
}
function runViaCargoInversion(payloadBase64) {
    return runViaRustBinaryInversion(payloadBase64);
}
function runBacklogAutoscalePrimitive(mode, data = {}, opts = {}) {
    const normalizedMode = cleanText(mode || '', 80).toLowerCase();
    if (!normalizedMode)
        return { ok: false, error: 'autoscale_mode_missing' };
    const fieldByMode = {
        default_backlog_autoscale_state: 'default_backlog_autoscale_state_input',
        normalize_backlog_autoscale_state: 'normalize_backlog_autoscale_state_input',
        spawn_allocated_cells: 'spawn_allocated_cells_input',
        spawn_capacity_boost_snapshot: 'spawn_capacity_boost_snapshot_input',
        inversion_maturity_score: 'inversion_maturity_score_input',
        plan: 'plan_input',
        batch_max: 'batch_input',
        dynamic_caps: 'dynamic_caps_input',
        token_usage: 'token_usage_input',
        normalize_queue: 'normalize_queue_input',
        criteria_gate: 'criteria_gate_input',
        structural_preview_criteria_failure: 'structural_preview_criteria_failure_input',
        policy_hold: 'policy_hold_input',
        policy_hold_result: 'policy_hold_result_input',
        no_progress_result: 'no_progress_result_input',
        attempt_run_event: 'attempt_run_event_input',
        safety_stop_run_event: 'safety_stop_run_event_input',
        non_yield_category: 'non_yield_category_input',
        non_yield_reason: 'non_yield_reason_input',
        proposal_type_from_run_event: 'proposal_type_from_run_event_input',
        run_event_objective_id: 'run_event_objective_id_input',
        run_event_proposal_id: 'run_event_proposal_id_input',
        capacity_counted_attempt_event: 'capacity_counted_attempt_event_input',
        repeat_gate_anchor: 'repeat_gate_anchor_input',
        score_only_result: 'score_only_result_input',
        score_only_failure_like: 'score_only_failure_like_input',
        gate_exhausted_attempt: 'gate_exhausted_attempt_input',
        consecutive_gate_exhausted_attempts: 'consecutive_gate_exhausted_attempts_input',
        runs_since_reset_index: 'runs_since_reset_index_input',
        attempt_event_indices: 'attempt_event_indices_input',
        capacity_counted_attempt_indices: 'capacity_counted_attempt_indices_input',
        consecutive_no_progress_runs: 'consecutive_no_progress_runs_input',
        shipped_count: 'shipped_count_input',
        executed_count_by_risk: 'executed_count_by_risk_input',
        run_result_tally: 'run_result_tally_input',
        qos_lane_usage: 'qos_lane_usage_input',
        eye_outcome_count_window: 'eye_outcome_count_window_input',
        eye_outcome_count_last_hours: 'eye_outcome_count_last_hours_input',
        sorted_counts: 'sorted_counts_input',
        normalize_proposal_status: 'normalize_proposal_status_input',
        proposal_status: 'proposal_status_input',
        proposal_status_for_queue_pressure: 'proposal_status_for_queue_pressure_input',
        minutes_since_ts: 'minutes_since_ts_input',
        date_window: 'date_window_input',
        in_window: 'in_window_input',
        exec_window_match: 'exec_window_match_input',
        start_of_next_utc_day: 'start_of_next_utc_day_input',
        iso_after_minutes: 'iso_after_minutes_input',
        execute_confidence_history_match: 'execute_confidence_history_match_input',
        execute_confidence_cooldown_key: 'execute_confidence_cooldown_key_input',
        qos_lane_weights: 'qos_lane_weights_input',
        proposal_outcome_status: 'proposal_outcome_status_input',
        queue_underflow_backfill: 'queue_underflow_backfill_input',
        proposal_risk_score: 'proposal_risk_score_input',
        proposal_score: 'proposal_score_input',
        proposal_admission_preview: 'proposal_admission_preview_input',
        impact_weight: 'impact_weight_input',
        risk_penalty: 'risk_penalty_input',
        estimate_tokens: 'estimate_tokens_input',
        proposal_remediation_depth: 'proposal_remediation_depth_input',
        proposal_dedup_key: 'proposal_dedup_key_input',
        proposal_semantic_fingerprint: 'proposal_semantic_fingerprint_input',
        semantic_token_similarity: 'semantic_token_similarity_input',
        semantic_context_comparable: 'semantic_context_comparable_input',
        semantic_near_duplicate_match: 'semantic_near_duplicate_match_input',
        expected_value_signal: 'expected_value_signal_input',
        budget_pacing_gate: 'budget_pacing_gate_input',
        capability_cap: 'capability_cap_input',
        strategy_rank_score: 'strategy_rank_score_input',
        strategy_rank_adjusted: 'strategy_rank_adjusted_input',
        trit_shadow_rank_score: 'trit_shadow_rank_score_input',
        strategy_circuit_cooldown: 'strategy_circuit_cooldown_input',
        strategy_trit_shadow_adjusted: 'strategy_trit_shadow_adjusted_input',
        non_yield_penalty_score: 'non_yield_penalty_score_input',
        collective_shadow_adjustments: 'collective_shadow_adjustments_input',
        strategy_trit_shadow_ranking_summary: 'strategy_trit_shadow_ranking_summary_input',
        shadow_scope_matches: 'shadow_scope_matches_input',
        collective_shadow_aggregate: 'collective_shadow_aggregate_input',
        value_signal_score: 'value_signal_score_input',
        composite_eligibility_score: 'composite_eligibility_score_input',
        time_to_value_score: 'time_to_value_score_input',
        value_density_score: 'value_density_score_input',
        normalize_directive_tier: 'normalize_directive_tier_input',
        directive_tier_weight: 'directive_tier_weight_input',
        directive_tier_min_share: 'directive_tier_min_share_input',
        directive_tier_coverage_bonus: 'directive_tier_coverage_bonus_input',
        directive_tier_reservation_need: 'directive_tier_reservation_need_input',
        pulse_objective_cooldown_active: 'pulse_objective_cooldown_active_input',
        directive_token_hits: 'directive_token_hits_input',
        to_stem: 'to_stem_input',
        normalize_directive_text: 'normalize_directive_text_input',
        tokenize_directive_text: 'tokenize_directive_text_input',
        normalize_spaces: 'normalize_spaces_input',
        parse_lower_list: 'parse_lower_list_input',
        canary_failed_checks_allowed: 'canary_failed_checks_allowed_input',
        proposal_text_blob: 'proposal_text_blob_input',
        percent_mentions_from_text: 'percent_mentions_from_text_input',
        optimization_min_delta_percent: 'optimization_min_delta_percent_input',
        source_eye_ref: 'source_eye_ref_input',
        normalized_risk: 'normalized_risk_input',
        parse_iso_ts: 'parse_iso_ts_input',
        extract_objective_id_token: 'extract_objective_id_token_input',
        normalize_value_currency_token: 'normalize_value_currency_token_input',
        list_value_currencies: 'list_value_currencies_input',
        infer_value_currencies_from_directive_bits: 'infer_value_currencies_from_directive_bits_input',
        has_linked_objective_entry: 'has_linked_objective_entry_input',
        verified_entry_outcome: 'verified_entry_outcome_input',
        verified_revenue_action: 'verified_revenue_action_input',
        minutes_until_next_utc_day: 'minutes_until_next_utc_day_input',
        age_hours: 'age_hours_input',
        url_domain: 'url_domain_input',
        domain_allowed: 'domain_allowed_input',
        is_execute_mode: 'is_execute_mode_input',
        execution_allowed_by_feature_flag: 'execution_allowed_by_feature_flag_input',
        is_tier1_objective_id: 'is_tier1_objective_id_input',
        is_tier1_candidate_objective: 'is_tier1_candidate_objective_input',
        needs_execution_quota: 'needs_execution_quota_input',
        normalize_criteria_metric: 'normalize_criteria_metric_input',
        escape_reg_exp: 'escape_reg_exp_input',
        tool_token_mentioned: 'tool_token_mentioned_input',
        policy_hold_reason_from_event: 'policy_hold_reason_from_event_input',
        strategy_marker_tokens: 'strategy_marker_tokens_input',
        capability_cooldown_key: 'capability_cooldown_key_input',
        readiness_retry_cooldown_key: 'readiness_retry_cooldown_key_input',
        source_eye_id: 'source_eye_id_input',
        deprioritized_source_proposal: 'deprioritized_source_proposal_input',
        composite_eligibility_min: 'composite_eligibility_min_input',
        clamp_threshold: 'clamp_threshold_input',
        applied_thresholds: 'applied_thresholds_input',
        extract_eye_from_evidence_ref: 'extract_eye_from_evidence_ref_input',
        total_outcomes: 'total_outcomes_input',
        derive_entity_bias: 'derive_entity_bias_input',
        strategy_profile: 'strategy_profile_input',
        active_strategy_variants: 'active_strategy_variants_input',
        strategy_scorecard_summaries: 'strategy_scorecard_summaries_input',
        outcome_fitness_policy: 'outcome_fitness_policy_input',
        load_eyes_map: 'load_eyes_map_input',
        fallback_directive_objective_ids: 'fallback_directive_objective_ids_input',
        queue_pressure_snapshot: 'queue_pressure_snapshot_input',
        parse_success_criteria_rows: 'parse_success_criteria_rows_input',
        collect_outcome_stats: 'collect_outcome_stats_input',
        subdirective_v2_signals: 'subdirective_v2_signals_input',
        build_overlay: 'build_overlay_input',
        has_adaptive_mutation_signal: 'has_adaptive_mutation_signal_input',
        adaptive_mutation_execution_guard: 'adaptive_mutation_execution_guard_input',
        strategy_selection: 'strategy_selection_input',
        calibration_deltas: 'calibration_deltas_input',
        strategy_admission_decision: 'strategy_admission_decision_input',
        expected_value_score: 'expected_value_score_input',
        suggest_run_batch_max: 'suggest_run_batch_max_input',
        backlog_autoscale_snapshot: 'backlog_autoscale_snapshot_input',
        admission_summary: 'admission_summary_input',
        unknown_type_quarantine_decision: 'unknown_type_quarantine_decision_input',
        infer_optimization_delta: 'infer_optimization_delta_input',
        optimization_intent_proposal: 'optimization_intent_proposal_input',
        unlinked_optimization_admission: 'unlinked_optimization_admission_input',
        optimization_good_enough: 'optimization_good_enough_input',
        proposal_dependency_summary: 'proposal_dependency_summary_input',
        choose_selection_mode: 'choose_selection_mode_input',
        explore_quota_for_day: 'explore_quota_for_day_input',
        medium_risk_thresholds: 'medium_risk_thresholds_input',
        medium_risk_gate_decision: 'medium_risk_gate_decision_input',
        route_block_prefilter: 'route_block_prefilter_input',
        route_execution_sample_event: 'route_execution_sample_event_input',
        route_block_telemetry_summary: 'route_block_telemetry_summary_input',
        is_stub_proposal: 'is_stub_proposal_input',
        recent_autonomy_run_events: 'recent_autonomy_run_events_input',
        proposal_meta_index: 'proposal_meta_index_input',
        new_log_events: 'new_log_events_input',
        outcome_buckets: 'outcome_buckets_input',
        recent_run_events: 'recent_run_events_input',
        all_decision_events: 'all_decision_events_input',
        cooldown_active_state: 'cooldown_active_state_input',
        bump_count: 'bump_count_input',
        lock_age_minutes: 'lock_age_minutes_input',
        hash_obj: 'hash_obj_input',
        assess_success_criteria_quality: 'assess_success_criteria_quality_input',
        manual_gate_prefilter: 'manual_gate_prefilter_input',
        execute_confidence_cooldown_active: 'execute_confidence_cooldown_active_input',
        top_biases_summary: 'top_biases_summary_input',
        criteria_pattern_penalty: 'criteria_pattern_penalty_input',
        strategy_threshold_overrides: 'strategy_threshold_overrides_input',
        effective_allowed_risks: 'effective_allowed_risks_input',
        directive_pulse_stats: 'directive_pulse_stats_input',
        compile_directive_pulse_objectives: 'compile_directive_pulse_objectives_input',
        directive_pulse_objectives_profile: 'directive_pulse_objectives_profile_input',
        recent_directive_pulse_cooldown_count: 'recent_directive_pulse_cooldown_count_input',
        proposal_directive_text: 'proposal_directive_text_input',
        objective_ids_from_pulse_context: 'objective_ids_from_pulse_context_input',
        policy_hold_objective_context: 'policy_hold_objective_context_input',
        proposal_semantic_objective_id: 'proposal_semantic_objective_id_input',
        criteria_pattern_keys: 'criteria_pattern_keys_input',
        success_criteria_requirement: 'success_criteria_requirement_input',
        success_criteria_policy_for_proposal: 'success_criteria_policy_for_proposal_input',
        capability_descriptor: 'capability_descriptor_input',
        normalize_token_usage_shape: 'normalize_token_usage_shape_input',
        directive_pulse_context: 'directive_pulse_context_input',
        is_directive_clarification_proposal: 'is_directive_clarification_proposal_input',
        is_directive_decomposition_proposal: 'is_directive_decomposition_proposal_input',
        sanitize_directive_objective_id: 'sanitize_directive_objective_id_input',
        sanitized_directive_id_list: 'sanitized_directive_id_list_input',
        parse_first_json_line: 'parse_first_json_line_input',
        parse_json_objects_from_text: 'parse_json_objects_from_text_input',
        read_path_value: 'read_path_value_input',
        number_or_null: 'number_or_null_input',
        choose_evidence_selection_mode: 'choose_evidence_selection_mode_input',
        truthy_flag: 'truthy_flag_input',
        falsey_flag: 'falsey_flag_input',
        stable_selection_index: 'stable_selection_index_input',
        as_string_array: 'as_string_array_input',
        uniq_sorted: 'uniq_sorted_input',
        normalize_model_ids: 'normalize_model_ids_input',
        selected_model_from_run_event: 'selected_model_from_run_event_input',
        read_first_numeric_metric: 'read_first_numeric_metric_input',
        parse_arg: 'parse_arg_input',
        date_arg_or_today: 'date_arg_or_today_input',
        has_env_numeric_override: 'has_env_numeric_override_input',
        coalesce_numeric: 'coalesce_numeric_input',
        clamp_number: 'clamp_number_input',
        list_proposal_files: 'list_proposal_files_input',
        latest_proposal_date: 'latest_proposal_date_input',
        parse_directive_file_arg: 'parse_directive_file_arg_input',
        parse_directive_objective_arg: 'parse_directive_objective_arg_input',
        now_iso: 'now_iso_input',
        today_str: 'today_str_input',
        human_canary_override_approval_phrase: 'human_canary_override_approval_phrase_input',
        parse_human_canary_override_state: 'parse_human_canary_override_state_input',
        daily_budget_path: 'daily_budget_path_input',
        runs_path_for: 'runs_path_for_input',
        effective_tier1_policy: 'effective_tier1_policy_input',
        compact_tier1_exception: 'compact_tier1_exception_input',
        next_human_escalation_clear_at: 'next_human_escalation_clear_at_input',
        model_catalog_canary_thresholds: 'model_catalog_canary_thresholds_input',
        default_criteria_pattern_memory: 'default_criteria_pattern_memory_input',
        strategy_execution_mode_effective: 'strategy_execution_mode_effective_input',
        strategy_canary_exec_limit_effective: 'strategy_canary_exec_limit_effective_input',
        strategy_exploration_effective: 'strategy_exploration_effective_input',
        strategy_budget_effective: 'strategy_budget_effective_input',
        preexec_verdict_from_signals: 'preexec_verdict_from_signals_input',
        score_only_proposal_churn: 'score_only_proposal_churn_input',
        success_criteria_quality_audit: 'success_criteria_quality_audit_input',
        detect_eyes_terminology_drift: 'detect_eyes_terminology_drift_input',
        normalize_stored_proposal_row: 'normalize_stored_proposal_row_input',
        recent_proposal_key_counts: 'recent_proposal_key_counts_input',
        capability_attempt_count_for_date: 'capability_attempt_count_for_date_input',
        capability_outcome_stats_in_window: 'capability_outcome_stats_in_window_input',
        execute_confidence_history: 'execute_confidence_history_input',
        execute_confidence_policy: 'execute_confidence_policy_input',
        directive_fit_assessment: 'directive_fit_assessment_input',
        signal_quality_assessment: 'signal_quality_assessment_input',
        actionability_assessment: 'actionability_assessment_input',
        directive_clarification_exec_spec: 'directive_clarification_exec_spec_input',
        directive_decomposition_exec_spec: 'directive_decomposition_exec_spec_input',
        parse_actuation_spec: 'parse_actuation_spec_input',
        task_from_proposal: 'task_from_proposal_input',
        parse_objective_id_from_evidence_refs: 'parse_objective_id_from_evidence_refs_input',
        parse_objective_id_from_command: 'parse_objective_id_from_command_input',
        objective_id_for_execution: 'objective_id_for_execution_input',
        short_text: 'short_text_input',
        normalized_signal_status: 'normalized_signal_status_input',
        execution_reserve_snapshot: 'execution_reserve_snapshot_input',
        qos_lane_share_cap_exceeded: 'qos_lane_share_cap_exceeded_input',
        qos_lane_from_candidate: 'qos_lane_from_candidate_input',
        estimate_tokens_for_candidate: 'estimate_tokens_for_candidate_input',
        route_execution_policy_hold: 'route_execution_policy_hold_input',
        policy_hold_pressure: 'policy_hold_pressure_input',
        policy_hold_pattern: 'policy_hold_pattern_input',
        policy_hold_latest_event: 'policy_hold_latest_event_input',
        policy_hold_cooldown: 'policy_hold_cooldown_input',
        policy_hold_run_event: 'policy_hold_run_event_input',
        dod_evidence_diff: 'dod_evidence_diff_input',
        receipt_verdict: 'receipt_verdict_input'
    };
    const field = fieldByMode[normalizedMode];
    if (!field)
        return { ok: false, error: `autoscale_mode_unsupported:${normalizedMode}` };
    const request = { mode: normalizedMode };
    request[field] = data && typeof data === 'object' ? data : {};
    const payloadBase64 = Buffer.from(JSON.stringify(request), 'utf8').toString('base64');
    const bin = runViaRustBinary(payloadBase64);
    if (bin.ok)
        return bin;
    if (opts.allow_cli_fallback === false)
        return bin;
    return runViaCargo(payloadBase64);
}
function runInversionPrimitive(mode, data = {}, opts = {}) {
    const normalizedMode = cleanText(mode || '', 80).toLowerCase();
    if (!normalizedMode)
        return { ok: false, error: 'inversion_mode_missing' };
    const fieldByMode = {
        normalize_impact: 'normalize_impact_input',
        normalize_mode: 'normalize_mode_input',
        normalize_target: 'normalize_target_input',
        normalize_result: 'normalize_result_input',
        objective_id_valid: 'objective_id_valid_input',
        trit_vector_from_input: 'trit_vector_from_input_input',
        jaccard_similarity: 'jaccard_similarity_input',
        trit_similarity: 'trit_similarity_input',
        certainty_threshold: 'certainty_threshold_input',
        max_target_rank: 'max_target_rank_input',
        creative_penalty: 'creative_penalty_input',
        extract_bullets: 'extract_bullets_input',
        extract_list_items: 'extract_list_items_input',
        parse_system_internal_permission: 'parse_system_internal_permission_input',
        parse_soul_token_data_pass_rules: 'parse_soul_token_data_pass_rules_input',
        ensure_system_passed_section: 'ensure_system_passed_section_input',
        system_passed_payload_hash: 'system_passed_payload_hash_input',
        build_lens_position: 'build_lens_position_input',
        build_conclave_proposal_summary: 'build_conclave_proposal_summary_input',
        conclave_high_risk_flags: 'conclave_high_risk_flags_input',
        tokenize_text: 'tokenize_text_input',
        normalize_list: 'normalize_list_input',
        normalize_text_list: 'normalize_text_list_input',
        parse_json_from_stdout: 'parse_json_from_stdout_input',
        parse_args: 'parse_args_input',
        library_match_score: 'library_match_score_input',
        known_failure_pressure: 'known_failure_pressure_input',
        has_signal_term_match: 'has_signal_term_match_input',
        count_axiom_signal_groups: 'count_axiom_signal_groups_input',
        effective_first_n_human_veto_uses: 'effective_first_n_human_veto_uses_input',
        normalize_band_map: 'normalize_band_map_input',
        normalize_impact_map: 'normalize_impact_map_input',
        normalize_target_map: 'normalize_target_map_input',
        normalize_target_policy: 'normalize_target_policy_input',
        window_days_for_target: 'window_days_for_target_input',
        tier_retention_days: 'tier_retention_days_input',
        parse_candidate_list_from_llm_payload: 'parse_candidate_list_from_llm_payload_input',
        heuristic_filter_candidates: 'heuristic_filter_candidates_input',
        score_trial: 'score_trial_input',
        mutate_trial_candidates: 'mutate_trial_candidates_input',
        normalize_iso_events: 'normalize_iso_events_input',
        expand_legacy_count_to_events: 'expand_legacy_count_to_events_input',
        normalize_tier_event_map: 'normalize_tier_event_map_input',
        default_tier_scope: 'default_tier_scope_input',
        normalize_tier_scope: 'normalize_tier_scope_input',
        default_tier_governance_state: 'default_tier_governance_state_input',
        clone_tier_scope: 'clone_tier_scope_input',
        prune_tier_scope_events: 'prune_tier_scope_events_input',
        load_tier_governance_state: 'load_tier_governance_state_input',
        save_tier_governance_state: 'save_tier_governance_state_input',
        push_tier_event: 'push_tier_event_input',
        add_tier_event: 'add_tier_event_input',
        increment_live_apply_attempt: 'increment_live_apply_attempt_input',
        increment_live_apply_success: 'increment_live_apply_success_input',
        increment_live_apply_safe_abort: 'increment_live_apply_safe_abort_input',
        update_shadow_trial_counters: 'update_shadow_trial_counters_input',
        count_tier_events: 'count_tier_events_input',
        effective_window_days_for_target: 'effective_window_days_for_target_input',
        to_date: 'to_date_input',
        parse_ts_ms: 'parse_ts_ms_input',
        add_minutes: 'add_minutes_input',
        clamp_int: 'clamp_int_input',
        clamp_number: 'clamp_number_input',
        to_bool: 'to_bool_input',
        clean_text: 'clean_text_input',
        normalize_token: 'normalize_token_input',
        normalize_word_token: 'normalize_word_token_input',
        band_to_index: 'band_to_index_input',
        escape_regex: 'escape_regex_input',
        pattern_to_word_regex: 'pattern_to_word_regex_input',
        stable_id: 'stable_id_input',
        rel_path: 'rel_path_input',
        normalize_axiom_pattern: 'normalize_axiom_pattern_input',
        normalize_axiom_signal_terms: 'normalize_axiom_signal_terms_input',
        normalize_observer_id: 'normalize_observer_id_input',
        extract_numeric: 'extract_numeric_input',
        pick_first_numeric: 'pick_first_numeric_input',
        safe_rel_path: 'safe_rel_path_input',
        now_iso: 'now_iso_input',
        default_tier_event_map: 'default_tier_event_map_input',
        coerce_tier_event_map: 'coerce_tier_event_map_input',
        get_tier_scope: 'get_tier_scope_input',
        default_harness_state: 'default_harness_state_input',
        default_first_principle_lock_state: 'default_first_principle_lock_state_input',
        default_maturity_state: 'default_maturity_state_input',
        principle_key_for_session: 'principle_key_for_session_input',
        normalize_objective_arg: 'normalize_objective_arg_input',
        maturity_band_order: 'maturity_band_order_input',
        current_runtime_mode: 'current_runtime_mode_input',
        read_drift_from_state_file: 'read_drift_from_state_file_input',
        resolve_lens_gate_drift: 'resolve_lens_gate_drift_input',
        resolve_parity_confidence: 'resolve_parity_confidence_input',
        compute_attractor_score: 'compute_attractor_score_input',
        build_output_interfaces: 'build_output_interfaces_input',
        build_code_change_proposal_draft: 'build_code_change_proposal_draft_input',
        normalize_library_row: 'normalize_library_row_input',
        ensure_dir: 'ensure_dir_input',
        read_json: 'read_json_input',
        read_jsonl: 'read_jsonl_input',
        write_json_atomic: 'write_json_atomic_input',
        append_jsonl: 'append_jsonl_input',
        read_text: 'read_text_input',
        latest_json_file_in_dir: 'latest_json_file_in_dir_input',
        normalize_output_channel: 'normalize_output_channel_input',
        normalize_repo_path: 'normalize_repo_path_input',
        runtime_paths: 'runtime_paths_input',
        normalize_axiom_list: 'normalize_axiom_list_input',
        normalize_harness_suite: 'normalize_harness_suite_input',
        load_harness_state: 'load_harness_state_input',
        save_harness_state: 'save_harness_state_input',
        load_first_principle_lock_state: 'load_first_principle_lock_state_input',
        save_first_principle_lock_state: 'save_first_principle_lock_state_input',
        check_first_principle_downgrade: 'check_first_principle_downgrade_input',
        upsert_first_principle_lock: 'upsert_first_principle_lock_input',
        load_observer_approvals: 'load_observer_approvals_input',
        append_observer_approval: 'append_observer_approval_input',
        count_observer_approvals: 'count_observer_approvals_input',
        ensure_correspondence_file: 'ensure_correspondence_file_input',
        load_maturity_state: 'load_maturity_state_input',
        save_maturity_state: 'save_maturity_state_input',
        load_active_sessions: 'load_active_sessions_input',
        save_active_sessions: 'save_active_sessions_input',
        emit_event: 'emit_event_input',
        append_persona_lens_gate_receipt: 'append_persona_lens_gate_receipt_input',
        append_conclave_correspondence: 'append_conclave_correspondence_input',
        persist_decision: 'persist_decision_input',
        persist_interface_envelope: 'persist_interface_envelope_input',
        trim_library: 'trim_library_input',
        detect_immutable_axiom_violation: 'detect_immutable_axiom_violation_input',
        compute_maturity_score: 'compute_maturity_score_input',
        select_library_candidates: 'select_library_candidates_input',
        parse_lane_decision: 'parse_lane_decision_input',
        sweep_expired_sessions: 'sweep_expired_sessions_input',
        load_impossibility_signals: 'load_impossibility_signals_input',
        evaluate_impossibility_trigger: 'evaluate_impossibility_trigger_input',
        extract_first_principle: 'extract_first_principle_input',
        extract_failure_cluster_principle: 'extract_failure_cluster_principle_input',
        persist_first_principle: 'persist_first_principle_input'
    };
    const field = fieldByMode[normalizedMode];
    if (!field)
        return { ok: false, error: `inversion_mode_unsupported:${normalizedMode}` };
    const request = { mode: normalizedMode };
    request[field] = data && typeof data === 'object' ? data : {};
    const payloadBase64 = Buffer.from(JSON.stringify(request), 'utf8').toString('base64');
    const bin = runViaRustBinaryInversion(payloadBase64);
    if (bin.ok)
        return bin;
    if (opts.allow_cli_fallback === false)
        return bin;
    return runViaCargoInversion(payloadBase64);
}
module.exports = {
    runBacklogAutoscalePrimitive,
    runViaRustBinary,
    runViaCargo,
    runInversionPrimitive,
    runViaRustBinaryInversion,
    runViaCargoInversion
};
