#!/usr/bin/env node
'use strict';

/**
 * directive_intake.js
 *
 * Purpose:
 * - Intake/generate Tier 1 directive YAML with required scope/specificity fields.
 * - Validate directives using SMART-lite gate before write.
 *
 * Usage:
 *   node systems/security/directive_intake.js new --id=T1_example_v1 [--interactive] [--force]
 *   node systems/security/directive_intake.js validate --file=config/directives/T1_example_v1.yaml
 *   node systems/security/directive_intake.js --help
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');
const { spawnSync } = require('child_process');
const { validateTier1DirectiveQuality } = require('../../lib/directive_resolver.js');

const REPO_ROOT = path.resolve(__dirname, '..', '..');

function usage() {
  console.log('Usage:');
  console.log('  node systems/security/directive_intake.js new --id=T1_example_v1 [--interactive] [--force]');
  console.log('    Optional fields:');
  console.log('      --primary="..." --timebound="..."');
  console.log('      --scope-in="a,b" --scope-out="x,y"');
  console.log('      --leading="m1,m2" --lagging="k1,k2"');
  console.log('      --approval-gates="gate1,gate2"');
  console.log('      --risk-limits="max_drawdown_pct=10,max_single_bet_pct=2,max_monthly_burn=50000"');
  console.log('  node systems/security/directive_intake.js validate --file=config/directives/T1_example_v1.yaml');
  console.log('  node systems/security/directive_intake.js --help');
}

function parseArgs(argv) {
  const out = { _: [] };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (!a.startsWith('--')) {
      out._.push(a);
      continue;
    }
    const eq = a.indexOf('=');
    if (eq >= 0) {
      out[a.slice(2, eq)] = a.slice(eq + 1);
      continue;
    }
    const key = a.slice(2);
    const next = argv[i + 1];
    if (next != null && !String(next).startsWith('--')) {
      out[key] = next;
      i += 1;
      continue;
    }
    out[key] = true;
  }
  return out;
}

function asList(v) {
  return String(v || '')
    .split(',')
    .map((x) => String(x || '').trim())
    .filter(Boolean);
}

function normalizeDirectiveId(v) {
  const raw = String(v || '').trim();
  if (!raw) return '';
  const cleaned = raw.replace(/[^a-zA-Z0-9_]/g, '_');
  return cleaned.startsWith('T1_') ? cleaned : `T1_${cleaned}`;
}

function parseRiskLimits(v) {
  const out = {};
  const parts = asList(v);
  for (const part of parts) {
    const idx = part.indexOf('=');
    if (idx <= 0) continue;
    const k = part.slice(0, idx).trim();
    const vv = part.slice(idx + 1).trim();
    if (!k || !vv) continue;
    const n = Number(vv);
    out[k] = Number.isFinite(n) ? n : vv;
  }
  return out;
}

function toYamlSafe(v) {
  const s = String(v == null ? '' : v).replace(/"/g, '\\"');
  return `"${s}"`;
}

function yamlList(arr, indent = 4) {
  const pad = ' '.repeat(indent);
  const a = Array.isArray(arr) ? arr.filter(Boolean) : [];
  if (!a.length) return `${pad}- "TBD"`;
  return a.map((x) => `${pad}- ${toYamlSafe(x)}`).join('\n');
}

function yamlObject(obj, indent = 4) {
  const pad = ' '.repeat(indent);
  const src = obj && typeof obj === 'object' ? obj : {};
  const keys = Object.keys(src).sort((a, b) => a.localeCompare(b));
  if (!keys.length) return `${pad}placeholder_limit: "TBD"`;
  return keys.map((k) => {
    const v = src[k];
    if (typeof v === 'number' && Number.isFinite(v)) return `${pad}${k}: ${v}`;
    return `${pad}${k}: ${toYamlSafe(v)}`;
  }).join('\n');
}

function buildTier1DirectiveYaml(input) {
  const id = normalizeDirectiveId(input && input.id);
  const primary = String((input && input.primary) || '').trim() || 'TBD objective';
  const description = String((input && input.description) || '').trim() || primary;
  const timebound = String((input && input.timebound) || '').trim();
  const scopeIn = Array.isArray(input && input.scope_in) ? input.scope_in : [];
  const scopeOut = Array.isArray(input && input.scope_out) ? input.scope_out : [];
  const leading = Array.isArray(input && input.leading) ? input.leading : [];
  const lagging = Array.isArray(input && input.lagging) ? input.lagging : [];
  const approvalGates = Array.isArray(input && input.approval_gates) ? input.approval_gates : [];
  const riskLimits = input && input.risk_limits ? input.risk_limits : {};
  const version = String((input && input.version) || '1.0.0');
  const parentCollection = String((input && input.parent_collection) || 'T1_northstars');

  return [
    `# Tier 1 Strategic Directive: ${id}`,
    '# Generated by directive_intake.js',
    '',
    'metadata:',
    `  id: ${id}`,
    '  tier: 1',
    `  version: "${version}"`,
    `  description: ${toYamlSafe(description)}`,
    `  parent_collection: ${toYamlSafe(parentCollection)}`,
    '',
    'intent:',
    `  primary: ${toYamlSafe(primary)}`,
    '  definitions:',
    `    timeframe: ${toYamlSafe(timebound || 'TBD')}`,
    '',
    'constraints:',
    '  risk_limits:',
    yamlObject(riskLimits, 4),
    '  operational:',
    '    require_diversification: true',
    '',
    'success_metrics:',
    '  leading:',
    yamlList(leading, 4),
    '  lagging:',
    yamlList(lagging, 4),
    '',
    'scope:',
    '  included:',
    yamlList(scopeIn, 4),
    '  excluded:',
    yamlList(scopeOut, 4),
    '',
    'approval_policy:',
    '  inherits: T0_invariants',
    '  additional_gates:',
    yamlList(approvalGates, 4),
    ''
  ].join('\n');
}

function promptPlanForMissing(missing) {
  const m = new Set(Array.isArray(missing) ? missing : []);
  const plan = [];
  if (m.has('intent.primary')) {
    plan.push({ key: 'primary', prompt: 'Specific objective (intent.primary): ' });
  }
  if (m.has('intent.definitions_timebound') || m.has('intent.timebound_signal')) {
    plan.push({ key: 'timebound', prompt: 'Time-bound target (e.g. by 2026-12-31 or within 6 months): ' });
  }
  if (m.has('scope.included')) {
    plan.push({ key: 'scope_in', prompt: 'Scope included (comma-separated): ', parse: asList });
  }
  if (m.has('scope.excluded')) {
    plan.push({ key: 'scope_out', prompt: 'Scope excluded (comma-separated): ', parse: asList });
  }
  if (m.has('constraints.risk_limits')) {
    plan.push({
      key: 'risk_limits',
      prompt: 'Risk limits key=value list (comma-separated): ',
      parse: parseRiskLimits
    });
  }
  if (m.has('success_metrics.leading')) {
    plan.push({ key: 'leading', prompt: 'Leading metrics (comma-separated): ', parse: asList });
  }
  if (m.has('success_metrics.lagging')) {
    plan.push({ key: 'lagging', prompt: 'Lagging metrics (comma-separated): ', parse: asList });
  }
  if (m.has('approval_policy.additional_gates')) {
    plan.push({ key: 'approval_gates', prompt: 'Approval gates (comma-separated): ', parse: asList });
  }
  return plan;
}

async function promptMissingFields(input, missing) {
  const plan = promptPlanForMissing(missing);
  if (!plan.length) return input;
  const next = { ...(input || {}) };
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  try {
    for (const item of plan) {
      const value = await new Promise((resolve) => rl.question(item.prompt, resolve));
      const trimmed = String(value || '').trim();
      if (!trimmed) continue;
      next[item.key] = typeof item.parse === 'function' ? item.parse(trimmed) : trimmed;
    }
    return next;
  } finally {
    rl.close();
  }
}

function checkGuardOrExit(relFile) {
  const guardPath = path.join(REPO_ROOT, 'systems', 'security', 'guard.js');
  const r = spawnSync(process.execPath, [guardPath, `--files=${relFile}`], {
    cwd: REPO_ROOT,
    encoding: 'utf8',
    env: process.env
  });
  if (r.status === 0) return;
  const stderr = String(r.stderr || '').trim();
  const stdout = String(r.stdout || '').trim();
  if (stderr) process.stderr.write(`${stderr}\n`);
  if (stdout) process.stderr.write(`${stdout}\n`);
  process.exit(r.status == null ? 1 : r.status);
}

function failWithQuality(quality) {
  process.stderr.write('directive_intake: Tier 1 directive is underspecified.\n');
  if (Array.isArray(quality.missing) && quality.missing.length) {
    process.stderr.write(`missing fields: ${quality.missing.join(', ')}\n`);
  }
  if (Array.isArray(quality.questions) && quality.questions.length) {
    process.stderr.write('required clarifications:\n');
    for (const q of quality.questions) process.stderr.write(`- ${q}\n`);
  }
}

function baseInputFromArgs(args) {
  return {
    id: normalizeDirectiveId(args.id),
    version: String(args.version || '1.0.0'),
    parent_collection: String(args['parent-collection'] || args.parent_collection || 'T1_northstars'),
    description: String(args.description || '').trim(),
    primary: String(args.primary || '').trim(),
    timebound: String(args.timebound || '').trim(),
    scope_in: asList(args['scope-in'] || args.scope_in),
    scope_out: asList(args['scope-out'] || args.scope_out),
    leading: asList(args.leading),
    lagging: asList(args.lagging),
    approval_gates: asList(args['approval-gates'] || args.approval_gates),
    risk_limits: parseRiskLimits(args['risk-limits'] || args.risk_limits)
  };
}

function cmdValidate(args) {
  const fileArg = String(args.file || '').trim();
  if (!fileArg) {
    console.error('directive_intake: validate requires --file=<path>');
    process.exit(2);
  }
  const fileAbs = path.resolve(REPO_ROOT, fileArg);
  if (!fileAbs.startsWith(REPO_ROOT + path.sep) || !fs.existsSync(fileAbs)) {
    console.error(`directive_intake: file not found: ${fileArg}`);
    process.exit(2);
  }
  const text = fs.readFileSync(fileAbs, 'utf8');
  const idGuess = path.basename(fileAbs).replace(/\.ya?ml$/i, '');
  const quality = validateTier1DirectiveQuality(text, idGuess);
  process.stdout.write(JSON.stringify({
    ok: quality.ok === true,
    file: path.relative(REPO_ROOT, fileAbs).replace(/\\/g, '/'),
    missing: quality.missing || [],
    questions: quality.questions || []
  }, null, 2) + '\n');
  if (!quality.ok) process.exit(1);
}

async function cmdNew(args) {
  let input = baseInputFromArgs(args);
  if (!input.id) {
    console.error('directive_intake: new requires --id=<directive_id>');
    process.exit(2);
  }
  if (!/^T1_[A-Za-z0-9_]+$/.test(input.id)) {
    console.error('directive_intake: id must match T1_<alnum_or_>');
    process.exit(2);
  }

  const interactive = args.interactive === true || (!args['no-interactive'] && process.stdin.isTTY === true);
  let content = buildTier1DirectiveYaml(input);
  let quality = validateTier1DirectiveQuality(content, input.id);

  if (!quality.ok && interactive) {
    input = await promptMissingFields(input, quality.missing || []);
    content = buildTier1DirectiveYaml(input);
    quality = validateTier1DirectiveQuality(content, input.id);
  }

  if (!quality.ok) {
    failWithQuality(quality);
    process.exit(2);
  }

  const relFile = `config/directives/${input.id}.yaml`;
  const absFile = path.join(REPO_ROOT, relFile);
  if (fs.existsSync(absFile) && args.force !== true) {
    console.error(`directive_intake: file exists (${relFile}); rerun with --force to overwrite`);
    process.exit(2);
  }

  checkGuardOrExit(relFile);
  fs.mkdirSync(path.dirname(absFile), { recursive: true });
  fs.writeFileSync(absFile, content, 'utf8');
  process.stdout.write(JSON.stringify({
    ok: true,
    file: relFile,
    directive_id: input.id,
    quality: 'pass'
  }, null, 2) + '\n');
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const cmd = String(args._[0] || '').trim().toLowerCase();
  if (!cmd || cmd === 'help' || cmd === '--help' || cmd === '-h' || args.help) {
    usage();
    process.exit(0);
  }
  if (cmd === 'validate') return cmdValidate(args);
  if (cmd === 'new') return cmdNew(args);

  console.error(`directive_intake: unknown command '${cmd}'`);
  usage();
  process.exit(2);
}

if (require.main === module) {
  main().catch((err) => {
    console.error(`directive_intake: ${String(err && err.message || err)}`);
    process.exit(1);
  });
}

module.exports = {
  parseArgs,
  asList,
  parseRiskLimits,
  normalizeDirectiveId,
  buildTier1DirectiveYaml,
  promptPlanForMissing
};
