#!/usr/bin/env node
'use strict';
export {};

/**
 * backlog_github_sync
 *
 * One-way mirror from canonical backlog registry -> GitHub Issues.
 * Safe defaults:
 * - dry-run by default
 * - explicit --apply=1 required for remote mutation
 */

const fs = require('fs');
const path = require('path');
const { spawnSync } = require('child_process');
const {
  ROOT,
  nowIso,
  parseArgs,
  cleanText,
  normalizeToken,
  toBool,
  clampInt,
  readJson,
  writeJsonAtomic,
  resolvePath,
  stableHash,
  emit
} = require('../../lib/queued_backlog_runtime');
const { loadPolicyRuntime } = require('../../lib/policy_runtime');
const { writeArtifactSet } = require('../../lib/state_artifact_contract');

type AnyObj = Record<string, any>;

const DEFAULT_POLICY_PATH = process.env.BACKLOG_GITHUB_SYNC_POLICY_PATH
  ? path.resolve(process.env.BACKLOG_GITHUB_SYNC_POLICY_PATH)
  : path.join(ROOT, 'config', 'backlog_github_sync_policy.json');

function usage() {
  console.log('Usage:');
  console.log('  node systems/ops/backlog_github_sync.js sync [--apply=1|0] [--strict=1|0] [--limit=<n>] [--statuses=s1,s2] [--policy=<path>]');
  console.log('  node systems/ops/backlog_github_sync.js check [--strict=1|0] [--policy=<path>]');
  console.log('  node systems/ops/backlog_github_sync.js status [--policy=<path>]');
}

function defaultPolicy() {
  return {
    version: '1.0',
    enabled: true,
    strict_default: true,
    dry_run_default: true,
    sync_statuses: ['queued', 'in_progress', 'blocked', 'proposed'],
    max_sync_rows: 200,
    paths: {
      registry_path: 'config/backlog_registry.json',
      state_path: 'state/ops/backlog_github_sync/state.json',
      latest_path: 'state/ops/backlog_github_sync/latest.json',
      receipts_path: 'state/ops/backlog_github_sync/receipts.jsonl'
    },
    github: {
      host: 'github.com',
      owner: 'jakerslam',
      repo: 'protheus',
      gh_bin: 'gh',
      auth_required: true,
      issue_title_prefix: '[Backlog]',
      body_header: 'Backlog mirror (generated by backlog_github_sync)',
      base_labels: ['backlog-mirror'],
      update_labels: true,
      create_missing_labels: false,
      close_on_archive: false,
      project_sync: false,
      project_v2_id: ''
    },
    workflow: {
      close_on_done: true,
      done_statuses: ['done', 'dropped', 'archived', 'obsolete'],
      require_pr_link_for_statuses: ['in_progress'],
      require_pr_link_strict: true,
      pr_link_markers: ['/pull/', 'github.com/']
    }
  };
}

function normalizeList(raw: unknown, fallback: string[] = []) {
  if (!Array.isArray(raw)) return fallback.slice();
  const out: string[] = [];
  for (const entry of raw) {
    const tok = normalizeToken(entry, 120);
    if (!tok) continue;
    if (!out.includes(tok)) out.push(tok);
  }
  return out.length ? out : fallback.slice();
}

function normalizeMarkers(raw: unknown, fallback: string[] = []) {
  if (!Array.isArray(raw)) return fallback.slice();
  const out: string[] = [];
  for (const entry of raw) {
    const tok = String(cleanText(entry, 120) || '').trim().toLowerCase();
    if (!tok) continue;
    if (!out.includes(tok)) out.push(tok);
  }
  return out.length ? out : fallback.slice();
}

function rel(filePath: string) {
  return path.relative(ROOT, filePath).replace(/\\/g, '/');
}

function loadPolicy(policyPath = DEFAULT_POLICY_PATH) {
  const base = defaultPolicy();
  const loaded = loadPolicyRuntime({
    policyPath,
    defaults: base
  });
  const raw = loaded.raw || {};
  const p = raw.paths && typeof raw.paths === 'object' ? raw.paths : {};
  const gh = raw.github && typeof raw.github === 'object' ? raw.github : {};
  const wf = raw.workflow && typeof raw.workflow === 'object' ? raw.workflow : {};

  return {
    version: cleanText(raw.version || base.version, 40) || base.version,
    enabled: toBool(raw.enabled, true),
    strict_default: toBool(raw.strict_default, base.strict_default),
    dry_run_default: toBool(raw.dry_run_default, base.dry_run_default),
    sync_statuses: normalizeList(raw.sync_statuses, base.sync_statuses),
    max_sync_rows: clampInt(raw.max_sync_rows, 1, 5000, base.max_sync_rows),
    paths: {
      registry_path: resolvePath(p.registry_path, base.paths.registry_path),
      state_path: resolvePath(p.state_path, base.paths.state_path),
      latest_path: resolvePath(p.latest_path, base.paths.latest_path),
      receipts_path: resolvePath(p.receipts_path, base.paths.receipts_path)
    },
    github: {
      host: cleanText(gh.host || base.github.host, 80) || base.github.host,
      owner: cleanText(gh.owner || base.github.owner, 120) || base.github.owner,
      repo: cleanText(gh.repo || base.github.repo, 120) || base.github.repo,
      gh_bin: cleanText(gh.gh_bin || base.github.gh_bin, 260) || base.github.gh_bin,
      auth_required: toBool(gh.auth_required, base.github.auth_required),
      issue_title_prefix: cleanText(gh.issue_title_prefix || base.github.issue_title_prefix, 80) || base.github.issue_title_prefix,
      body_header: cleanText(gh.body_header || base.github.body_header, 240) || base.github.body_header,
      base_labels: normalizeList(gh.base_labels, base.github.base_labels),
      update_labels: toBool(gh.update_labels, base.github.update_labels),
      create_missing_labels: toBool(gh.create_missing_labels, base.github.create_missing_labels),
      close_on_archive: toBool(gh.close_on_archive, base.github.close_on_archive),
      project_sync: toBool(gh.project_sync, base.github.project_sync),
      project_v2_id: cleanText(gh.project_v2_id || base.github.project_v2_id, 240) || ''
    },
    workflow: {
      close_on_done: toBool(wf.close_on_done, base.workflow.close_on_done),
      done_statuses: normalizeList(wf.done_statuses, base.workflow.done_statuses),
      require_pr_link_for_statuses: normalizeList(wf.require_pr_link_for_statuses, base.workflow.require_pr_link_for_statuses),
      require_pr_link_strict: toBool(wf.require_pr_link_strict, base.workflow.require_pr_link_strict),
      pr_link_markers: normalizeMarkers(wf.pr_link_markers, base.workflow.pr_link_markers)
    },
    policy_path: path.resolve(policyPath)
  };
}

function loadRegistry(policy: AnyObj) {
  const raw = readJson(policy.paths.registry_path, null);
  if (!raw || typeof raw !== 'object') {
    return {
      ok: false,
      error: 'registry_missing'
    };
  }
  const rows = Array.isArray(raw.rows) ? raw.rows : [];
  return {
    ok: true,
    schema_id: cleanText(raw.schema_id || '', 80),
    schema_version: cleanText(raw.schema_version || '', 24),
    generated_at: cleanText(raw.generated_at || '', 64),
    row_count: Number(raw.row_count || rows.length) || rows.length,
    rows
  };
}

function loadState(policy: AnyObj) {
  const base = {
    schema_id: 'backlog_github_sync_state',
    schema_version: '1.0',
    updated_at: null,
    github: {
      host: policy.github.host,
      owner: policy.github.owner,
      repo: policy.github.repo
    },
    issues_by_id: {}
  };
  const raw = readJson(policy.paths.state_path, {});
  const byId = raw && raw.issues_by_id && typeof raw.issues_by_id === 'object' ? raw.issues_by_id : {};
  const cleaned: AnyObj = {};
  for (const [id, row] of Object.entries(byId)) {
    const rid = cleanText(id, 120).replace(/`/g, '');
    if (!rid) continue;
    const item = row && typeof row === 'object' ? row : {};
    cleaned[rid] = {
      issue_number: Number(item.issue_number || 0) || null,
      issue_url: cleanText(item.issue_url || '', 500) || null,
      issue_node_id: cleanText(item.issue_node_id || '', 240) || null,
      issue_state: cleanText(item.issue_state || '', 40) || null,
      last_row_hash: cleanText(item.last_row_hash || '', 120) || null,
      last_row_status: normalizeToken(item.last_row_status || '', 80) || null,
      project_v2_item_id: cleanText(item.project_v2_item_id || '', 240) || null,
      last_synced_at: cleanText(item.last_synced_at || '', 64) || null,
      last_status_change_at: cleanText(item.last_status_change_at || '', 64) || null,
      last_content_change_at: cleanText(item.last_content_change_at || '', 64) || null
    };
  }
  return {
    ...base,
    ...raw,
    issues_by_id: cleaned
  };
}

function saveState(policy: AnyObj, state: AnyObj) {
  writeJsonAtomic(policy.paths.state_path, {
    schema_id: 'backlog_github_sync_state',
    schema_version: '1.0',
    updated_at: nowIso(),
    github: {
      host: policy.github.host,
      owner: policy.github.owner,
      repo: policy.github.repo
    },
    issues_by_id: state.issues_by_id || {}
  });
}

function runGh(policy: AnyObj, args: string[], input = '') {
  const proc = spawnSync(policy.github.gh_bin, args, {
    cwd: ROOT,
    encoding: 'utf8',
    input
  });
  const stdout = String(proc.stdout || '');
  const stderr = String(proc.stderr || '');
  let json = null;
  try {
    const trimmed = stdout.trim();
    if (trimmed) json = JSON.parse(trimmed);
  } catch {
    json = null;
  }
  return {
    ok: (Number.isFinite(proc.status) ? Number(proc.status) : 1) === 0,
    status: Number.isFinite(proc.status) ? Number(proc.status) : 1,
    stdout,
    stderr,
    json
  };
}

function ghAuthOk(policy: AnyObj) {
  const res = runGh(policy, ['auth', 'status', '--hostname', policy.github.host]);
  return res.ok === true;
}

function ghApi(policy: AnyObj, method: string, endpoint: string, payload: AnyObj | null = null) {
  const args = ['api', '-X', method, endpoint];
  if (payload && typeof payload === 'object') {
    args.push('--input', '-');
    return runGh(policy, args, JSON.stringify(payload));
  }
  return runGh(policy, args);
}

function ghGraphqlAddProjectItem(policy: AnyObj, projectId: string, issueNodeId: string) {
  const query = [
    'mutation($project:ID!, $content:ID!) {',
    '  addProjectV2ItemById(input:{projectId:$project, contentId:$content}) {',
    '    item { id }',
    '  }',
    '}'
  ].join('\n');
  const args = [
    'api',
    'graphql',
    '-f',
    `query=${query}`,
    '-F',
    `project=${projectId}`,
    '-F',
    `content=${issueNodeId}`
  ];
  return runGh(policy, args);
}

function chooseLabelColor(name: string) {
  const h = stableHash(String(name || ''), 6);
  return /^[0-9a-f]{6}$/i.test(h) ? h : '1f6feb';
}

function parseErrorText(res: AnyObj) {
  const bits = [String(res && res.stderr || ''), String(res && res.stdout || '')].join('\n').trim();
  if (!bits) return 'gh_command_failed';
  return cleanText(bits, 700);
}

function labelNameFromRow(prefix: string, value: string) {
  const token = normalizeToken(value, 40);
  if (!token) return '';
  return cleanText(`${prefix}:${token}`, 50);
}

function buildLabels(row: AnyObj, policy: AnyObj) {
  const labels: string[] = [];
  for (const item of policy.github.base_labels || []) {
    const lbl = cleanText(item, 50);
    if (lbl && !labels.includes(lbl)) labels.push(lbl);
  }
  const classLbl = labelNameFromRow('class', row.class || 'unknown');
  const waveLbl = labelNameFromRow('wave', row.wave || 'unknown');
  const statusLbl = labelNameFromRow('status', row.status || 'unknown');
  if (classLbl && !labels.includes(classLbl)) labels.push(classLbl);
  if (waveLbl && !labels.includes(waveLbl)) labels.push(waveLbl);
  if (statusLbl && !labels.includes(statusLbl)) labels.push(statusLbl);
  return labels;
}

function ensureLabel(policy: AnyObj, name: string) {
  if (!name) return { ok: true, action: 'skip_empty' };
  const owner = encodeURIComponent(policy.github.owner);
  const repo = encodeURIComponent(policy.github.repo);
  const encoded = encodeURIComponent(name);
  const getRes = ghApi(policy, 'GET', `repos/${owner}/${repo}/labels/${encoded}`);
  if (getRes.ok) return { ok: true, action: 'exists' };
  if (!policy.github.create_missing_labels) {
    return { ok: false, action: 'missing', error: 'label_missing_and_create_disabled' };
  }
  const createRes = ghApi(policy, 'POST', `repos/${owner}/${repo}/labels`, {
    name,
    color: chooseLabelColor(name),
    description: 'Managed by backlog_github_sync'
  });
  if (!createRes.ok) {
    return { ok: false, action: 'create_failed', error: parseErrorText(createRes) };
  }
  return { ok: true, action: 'created' };
}

function formatIssueTitle(row: AnyObj, policy: AnyObj) {
  const bits = [
    cleanText(policy.github.issue_title_prefix || '', 80),
    cleanText(row.id || '', 80),
    cleanText(row.title || '', 220)
  ].filter(Boolean);
  const title = cleanText(bits.join(' '), 240);
  return title || cleanText(row.id || 'Backlog Mirror', 120);
}

function formatIssueBody(row: AnyObj, rowHash: string, policy: AnyObj) {
  const deps = Array.isArray(row.dependencies) ? row.dependencies : [];
  const depLine = deps.length ? deps.join(', ') : '(none)';
  const lines = [
    `<!-- backlog-mirror-id:${row.id} -->`,
    `<!-- backlog-mirror-hash:${rowHash} -->`,
    '',
    `# ${policy.github.body_header}`,
    '',
    `- ID: \`${row.id}\``,
    `- Class: \`${cleanText(row.class || '', 80) || 'unknown'}\``,
    `- Wave: \`${cleanText(row.wave || '', 40) || 'unknown'}\``,
    `- Status: \`${cleanText(row.status || '', 80) || 'unknown'}\``,
    `- Dependencies: ${depLine}`,
    '',
    '## Problem',
    '',
    String(row.problem || '(missing)').trim(),
    '',
    '## Acceptance Criteria',
    '',
    String(row.acceptance || '(missing)').trim(),
    '',
    '_Source of truth: `config/backlog_registry.json` (generated from `UPGRADE_BACKLOG.md`)_',
    ''
  ];
  return lines.join('\n');
}

function parseIssue(payload: AnyObj) {
  if (!payload || typeof payload !== 'object') return null;
  if (payload.pull_request) return null;
  const number = Number(payload.number || 0);
  if (!number) return null;
  return {
    number,
    node_id: cleanText(payload.node_id || '', 240) || null,
    url: cleanText(payload.html_url || '', 500) || null,
    title: cleanText(payload.title || '', 240),
    body: String(payload.body || ''),
    state: normalizeToken(payload.state || 'open', 24) || 'open',
    updated_at: cleanText(payload.updated_at || '', 64) || null,
    labels: Array.isArray(payload.labels)
      ? payload.labels.map((row: AnyObj) => cleanText(row && row.name || '', 50)).filter(Boolean)
      : []
  };
}

function hasPrLink(body: string, markers: string[]) {
  const blob = String(body || '').toLowerCase();
  if (!blob) return false;
  for (const marker of markers || []) {
    const tok = String(marker || '').trim().toLowerCase();
    if (!tok) continue;
    if (blob.includes(tok)) return true;
  }
  return false;
}

function issueByNumber(policy: AnyObj, issueNumber: number) {
  if (!Number.isFinite(issueNumber) || issueNumber <= 0) return null;
  const owner = encodeURIComponent(policy.github.owner);
  const repo = encodeURIComponent(policy.github.repo);
  const res = ghApi(policy, 'GET', `repos/${owner}/${repo}/issues/${Math.floor(issueNumber)}`);
  if (!res.ok) return null;
  return parseIssue(res.json);
}

function issueByBacklogId(policy: AnyObj, backlogId: string) {
  const query = `repo:${policy.github.owner}/${policy.github.repo} is:issue \"backlog-mirror-id:${backlogId}\" in:body`;
  const endpoint = `search/issues?q=${encodeURIComponent(query)}&per_page=5`;
  const res = ghApi(policy, 'GET', endpoint);
  if (!res.ok || !res.json || !Array.isArray(res.json.items)) return null;
  for (const item of res.json.items) {
    const parsed = parseIssue(item);
    if (parsed) return parsed;
  }
  return null;
}

function upsertIssue(policy: AnyObj, row: AnyObj, issue: AnyObj | null, title: string, body: string, labels: string[], apply: boolean) {
  const owner = encodeURIComponent(policy.github.owner);
  const repo = encodeURIComponent(policy.github.repo);

  if (!apply) {
    return {
      ok: true,
      action: issue ? 'plan_update' : 'plan_create',
      issue: issue || null
    };
  }

  if (policy.github.update_labels && Array.isArray(labels) && labels.length > 0) {
    for (const label of labels) {
      const ensured = ensureLabel(policy, label);
      if (!ensured.ok) {
        return {
          ok: false,
          action: 'label_error',
          error: `label:${label}:${ensured.error || ensured.action}`
        };
      }
    }
  }

  if (!issue) {
    const payload: AnyObj = { title, body };
    if (policy.github.update_labels && labels.length) payload.labels = labels;
    let createRes = ghApi(policy, 'POST', `repos/${owner}/${repo}/issues`, payload);
    if (!createRes.ok && payload.labels) {
      const retryPayload = { title, body };
      createRes = ghApi(policy, 'POST', `repos/${owner}/${repo}/issues`, retryPayload);
    }
    if (!createRes.ok) {
      return {
        ok: false,
        action: 'create_failed',
        error: parseErrorText(createRes)
      };
    }
    return {
      ok: true,
      action: 'created',
      issue: parseIssue(createRes.json)
    };
  }

  const patchPayload: AnyObj = {
    title,
    body,
    state: 'open'
  };
  if (policy.github.update_labels) patchPayload.labels = labels;
  let patchRes = ghApi(policy, 'PATCH', `repos/${owner}/${repo}/issues/${issue.number}`, patchPayload);
  if (!patchRes.ok && patchPayload.labels) {
    const retryPayload = { title, body, state: 'open' };
    patchRes = ghApi(policy, 'PATCH', `repos/${owner}/${repo}/issues/${issue.number}`, retryPayload);
  }
  if (!patchRes.ok) {
    return {
      ok: false,
      action: 'update_failed',
      error: parseErrorText(patchRes)
    };
  }
  return {
    ok: true,
    action: 'updated',
    issue: parseIssue(patchRes.json)
  };
}

function maybeAttachProjectItem(policy: AnyObj, issue: AnyObj, stateRow: AnyObj) {
  if (!policy.github.project_sync) {
    return { ok: true, action: 'project_disabled', item_id: stateRow.project_v2_item_id || null };
  }
  const projectId = cleanText(policy.github.project_v2_id || '', 240);
  if (!projectId) {
    return { ok: false, action: 'project_missing_id', error: 'project_sync_enabled_without_project_v2_id' };
  }
  if (!issue || !issue.node_id) {
    return { ok: false, action: 'project_missing_issue_node_id', error: 'issue_node_id_missing' };
  }
  if (stateRow && stateRow.project_v2_item_id) {
    return { ok: true, action: 'project_already_linked', item_id: stateRow.project_v2_item_id };
  }
  const res = ghGraphqlAddProjectItem(policy, projectId, issue.node_id);
  if (!res.ok) {
    return { ok: false, action: 'project_attach_failed', error: parseErrorText(res) };
  }
  const itemId = cleanText(res.json && res.json.data && res.json.data.addProjectV2ItemById && res.json.data.addProjectV2ItemById.item && res.json.data.addProjectV2ItemById.item.id || '', 240) || null;
  return { ok: !!itemId, action: itemId ? 'project_attached' : 'project_attach_unknown', item_id: itemId };
}

function syncCmd(args: AnyObj, policy: AnyObj) {
  const strict = toBool(args.strict, policy.strict_default);
  const apply = toBool(args.apply, !policy.dry_run_default);
  const limit = clampInt(args.limit, 1, 5000, policy.max_sync_rows);
  const overrideStatuses = cleanText(args.statuses || args.status || '', 500);
  const statusSet = new Set<string>(
    overrideStatuses
      ? overrideStatuses.split(',').map((s) => normalizeToken(s, 80)).filter(Boolean)
      : policy.sync_statuses
  );

  const reg = loadRegistry(policy);
  if (!reg.ok) {
    const out = writeArtifactSet(
      { latestPath: policy.paths.latest_path, receiptsPath: policy.paths.receipts_path },
      {
        ok: false,
        type: 'backlog_github_sync',
        action: 'sync',
        ts: nowIso(),
        apply,
        strict,
        error: reg.error || 'registry_load_failed'
      },
      { schemaId: 'backlog_github_sync_receipt', schemaVersion: '1.0', artifactType: 'receipt' }
    );
    emit(out, strict ? 2 : 0);
  }

  const authOk = ghAuthOk(policy);
  if (apply && policy.github.auth_required && !authOk) {
    const out = writeArtifactSet(
      { latestPath: policy.paths.latest_path, receiptsPath: policy.paths.receipts_path },
      {
        ok: false,
        type: 'backlog_github_sync',
        action: 'sync',
        ts: nowIso(),
        apply,
        strict,
        auth_ok: false,
        error: 'github_auth_missing',
        detail: 'gh auth login required before --apply=1'
      },
      { schemaId: 'backlog_github_sync_receipt', schemaVersion: '1.0', artifactType: 'receipt' }
    );
    emit(out, strict ? 2 : 0);
  }

  const rows = (reg.rows || [])
    .filter((row: AnyObj) => statusSet.has(normalizeToken(row.status || '', 80)))
    .slice(0, limit)
    .map((row: AnyObj) => ({
      id: cleanText(row.id || '', 120).replace(/`/g, ''),
      class: normalizeToken(row.class || '', 80) || 'unknown',
      wave: cleanText(row.wave || '', 40) || 'V?',
      status: normalizeToken(row.status || '', 80) || 'queued',
      title: cleanText(row.title || '', 500),
      problem: cleanText(row.problem || '', 6000),
      acceptance: cleanText(row.acceptance || '', 8000),
      dependencies: Array.isArray(row.dependencies) ? row.dependencies.map((d: unknown) => cleanText(d, 120)).filter(Boolean) : []
    }))
    .filter((row: AnyObj) => !!row.id);
  const statusById = new Map<string, string>(
    (reg.rows || [])
      .map((row: AnyObj) => [cleanText(row && row.id || '', 120).replace(/`/g, ''), normalizeToken(row && row.status || '', 80)])
      .filter((pair: any[]) => !!pair[0] && !!pair[1])
  );

  const state = loadState(policy);
  const nextState: AnyObj = {
    ...state,
    issues_by_id: { ...(state.issues_by_id || {}) }
  };

  let created = 0;
  let updated = 0;
  let unchanged = 0;
  let skipped = 0;
  let closed_done = 0;
  const errors: AnyObj[] = [];
  const warnings: AnyObj[] = [];
  const actions: AnyObj[] = [];

  for (const row of rows) {
    const rowLabels = buildLabels(row, policy);
    const title = formatIssueTitle(row, policy);
    const rowHashSeed = JSON.stringify({
      id: row.id,
      class: row.class,
      wave: row.wave,
      status: row.status,
      title: row.title,
      problem: row.problem,
      acceptance: row.acceptance,
      dependencies: row.dependencies,
      labels: rowLabels
    });
    const rowHash = stableHash(rowHashSeed, 40);
    const body = formatIssueBody(row, rowHash, policy);

    const stateRow = nextState.issues_by_id[row.id] || {};
    const nowTs = nowIso();
    const prevStatus = normalizeToken(stateRow.last_row_status || '', 80) || null;
    const prevHash = cleanText(stateRow.last_row_hash || '', 80) || null;
    const statusChanged = !prevStatus || prevStatus !== row.status;
    const contentChanged = !prevHash || prevHash !== rowHash;
    const lastStatusChangeAt = statusChanged
      ? nowTs
      : (cleanText(stateRow.last_status_change_at || '', 64) || nowTs);
    const lastContentChangeAt = contentChanged
      ? nowTs
      : (cleanText(stateRow.last_content_change_at || '', 64) || nowTs);

    let issue: AnyObj | null = null;
    if (authOk) {
      if (stateRow && Number(stateRow.issue_number || 0) > 0) {
        const byNum = issueByNumber(policy, Number(stateRow.issue_number));
        if (byNum && String(byNum.body || '').includes(`backlog-mirror-id:${row.id}`)) {
          issue = byNum;
        }
      }
      if (!issue) {
        const byId = issueByBacklogId(policy, row.id);
        if (byId) issue = byId;
      }
    } else if (stateRow && Number(stateRow.issue_number || 0) > 0) {
      warnings.push({ id: row.id, warning: 'auth_missing_remote_not_verified' });
    }

    const hashMarker = `backlog-mirror-hash:${rowHash}`;
    const alreadySynced = issue
      ? String(issue.body || '').includes(hashMarker)
      : cleanText(stateRow.last_row_hash || '', 80) === rowHash;

    if (alreadySynced) {
      unchanged += 1;
      if (issue) {
        nextState.issues_by_id[row.id] = {
          ...stateRow,
          issue_number: issue.number,
          issue_url: issue.url,
          issue_node_id: issue.node_id,
          issue_state: issue.state,
          last_row_hash: rowHash,
          last_row_status: row.status,
          last_synced_at: nowTs,
          last_status_change_at: lastStatusChangeAt,
          last_content_change_at: lastContentChangeAt,
          project_v2_item_id: stateRow.project_v2_item_id || null
        };
      }
      actions.push({ id: row.id, action: 'unchanged', issue_number: issue ? issue.number : stateRow.issue_number || null });
      continue;
    }

    const upsert = upsertIssue(policy, row, issue, title, body, rowLabels, apply);
    if (!upsert.ok) {
      errors.push({ id: row.id, error: upsert.error || upsert.action || 'upsert_failed' });
      actions.push({ id: row.id, action: 'error', error: upsert.error || upsert.action || 'upsert_failed' });
      skipped += 1;
      continue;
    }

    const finalIssue = upsert.issue || issue || null;
    if (!finalIssue) {
      const action = upsert.action || 'planned';
      if (action === 'plan_create' || action === 'plan_update') {
        actions.push({ id: row.id, action });
        if (action === 'plan_create') created += 1;
        else updated += 1;
      } else {
        actions.push({ id: row.id, action: 'planned_unknown' });
      }
      continue;
    }

    if (upsert.action === 'created') created += 1;
    else if (upsert.action === 'updated') updated += 1;

    let projectItemId = stateRow.project_v2_item_id || null;
    if (apply && finalIssue) {
      const projectRes = maybeAttachProjectItem(policy, finalIssue, stateRow);
      if (!projectRes.ok) {
        warnings.push({ id: row.id, warning: projectRes.error || projectRes.action || 'project_attach_failed' });
      }
      if (projectRes.item_id) projectItemId = projectRes.item_id;
    }

    nextState.issues_by_id[row.id] = {
      issue_number: finalIssue.number,
      issue_url: finalIssue.url,
      issue_node_id: finalIssue.node_id,
      issue_state: finalIssue.state,
      last_row_hash: rowHash,
      last_row_status: row.status,
      project_v2_item_id: projectItemId,
      last_synced_at: nowTs,
      last_status_change_at: lastStatusChangeAt,
      last_content_change_at: lastContentChangeAt
    };

    actions.push({
      id: row.id,
      action: upsert.action,
      issue_number: finalIssue.number,
      issue_url: finalIssue.url || null
    });
  }

  if (apply && policy.github.close_on_archive) {
    const activeIds = new Set(rows.map((row: AnyObj) => row.id));
    for (const [id, item] of Object.entries(nextState.issues_by_id || {})) {
      const issueNum = Number(item && item.issue_number || 0);
      if (!issueNum || activeIds.has(id)) continue;
      if (!authOk) {
        warnings.push({ id, warning: 'close_on_archive_skipped_auth_missing' });
        continue;
      }
      const owner = encodeURIComponent(policy.github.owner);
      const repo = encodeURIComponent(policy.github.repo);
      const closeRes = ghApi(policy, 'PATCH', `repos/${owner}/${repo}/issues/${issueNum}`, { state: 'closed' });
      if (!closeRes.ok) {
        warnings.push({ id, warning: `archive_close_failed:${parseErrorText(closeRes)}` });
        continue;
      }
      const parsed = parseIssue(closeRes.json);
      if (parsed) {
        nextState.issues_by_id[id] = {
          ...item,
          issue_state: parsed.state,
          issue_url: parsed.url || item.issue_url || null,
          issue_node_id: parsed.node_id || item.issue_node_id || null,
          last_synced_at: nowIso()
        };
      }
    }
  }

  if (apply && policy.workflow && policy.workflow.close_on_done === true) {
    const doneStatuses = new Set(policy.workflow.done_statuses || []);
    for (const [id, item] of Object.entries(nextState.issues_by_id || {})) {
      const issueNum = Number(item && item.issue_number || 0);
      if (!issueNum) continue;
      const backlogStatus = normalizeToken(statusById.get(id) || '', 80);
      if (!backlogStatus || !doneStatuses.has(backlogStatus)) continue;
      if (!authOk) {
        warnings.push({ id, warning: 'close_on_done_skipped_auth_missing' });
        continue;
      }
      const owner = encodeURIComponent(policy.github.owner);
      const repo = encodeURIComponent(policy.github.repo);
      const closeRes = ghApi(policy, 'PATCH', `repos/${owner}/${repo}/issues/${issueNum}`, { state: 'closed' });
      if (!closeRes.ok) {
        warnings.push({ id, warning: `done_close_failed:${parseErrorText(closeRes)}` });
        continue;
      }
      const parsed = parseIssue(closeRes.json);
      closed_done += 1;
      actions.push({ id, action: 'closed_done', issue_number: issueNum });
      if (parsed) {
        nextState.issues_by_id[id] = {
          ...item,
          issue_state: parsed.state,
          issue_url: parsed.url || item.issue_url || null,
          issue_node_id: parsed.node_id || item.issue_node_id || null,
          last_synced_at: nowIso()
        };
      }
    }
  }

  if (apply) saveState(policy, nextState);

  const hardFailure = errors.length > 0;
  const out = writeArtifactSet(
    { latestPath: policy.paths.latest_path, receiptsPath: policy.paths.receipts_path },
    {
      ok: !hardFailure,
      type: 'backlog_github_sync',
      action: 'sync',
      ts: nowIso(),
      apply,
      strict,
      auth_ok: authOk,
      registry_row_count: Number(reg.row_count || 0),
      target_count: rows.length,
      created,
      updated,
      unchanged,
      skipped,
      closed_done,
      errors,
      warnings,
      actions: actions.slice(0, 80),
      policy_path: rel(policy.policy_path),
      registry_path: rel(policy.paths.registry_path),
      state_path: rel(policy.paths.state_path),
      latest_path: rel(policy.paths.latest_path),
      receipts_path: rel(policy.paths.receipts_path),
      github: {
        host: policy.github.host,
        owner: policy.github.owner,
        repo: policy.github.repo,
        project_sync: policy.github.project_sync === true
      }
    },
    { schemaId: 'backlog_github_sync_receipt', schemaVersion: '1.0', artifactType: 'receipt' }
  );

  emit(out, strict && hardFailure ? 2 : 0);
}

function checkCmd(args: AnyObj, policy: AnyObj) {
  const strict = toBool(args.strict, policy.strict_default);
  const reg = loadRegistry(policy);
  const state = loadState(policy);
  const authOk = ghAuthOk(policy);
  const statusById = new Map<string, string>(
    (reg.ok ? reg.rows : [])
      .map((row: AnyObj) => [cleanText(row && row.id || '', 120).replace(/`/g, ''), normalizeToken(row && row.status || '', 80)])
      .filter((pair: any[]) => !!pair[0] && !!pair[1])
  );

  const stateRows = state && state.issues_by_id && typeof state.issues_by_id === 'object'
    ? state.issues_by_id
    : {};

  const issueNumbers = new Map<number, string[]>();
  for (const [id, row] of Object.entries(stateRows)) {
    const num = Number(row && row.issue_number || 0);
    if (!num) continue;
    const list = issueNumbers.get(num) || [];
    list.push(id);
    issueNumbers.set(num, list);
  }
  const duplicateIssueNumbers = Array.from(issueNumbers.entries())
    .filter(([, ids]) => ids.length > 1)
    .map(([issue_number, ids]) => ({ issue_number, ids }));

  const registryIds = new Set<string>((reg.ok ? reg.rows : []).map((row: AnyObj) => cleanText(row.id || '', 120)).filter(Boolean));
  const staleMappings = Object.keys(stateRows).filter((id) => !registryIds.has(id));
  const missingPrLinks: AnyObj[] = [];
  const prLinkStatuses = new Set<string>(
    Array.isArray(policy.workflow && policy.workflow.require_pr_link_for_statuses)
      ? policy.workflow.require_pr_link_for_statuses
      : []
  );
  const prLinkMarkers = Array.isArray(policy.workflow && policy.workflow.pr_link_markers)
    ? policy.workflow.pr_link_markers
    : [];
  if (prLinkStatuses.size > 0) {
    for (const [id, status] of statusById.entries()) {
      if (!prLinkStatuses.has(status)) continue;
      const mapped = stateRows[id] && typeof stateRows[id] === 'object' ? stateRows[id] : null;
      if (!mapped || Number(mapped.issue_number || 0) <= 0) {
        missingPrLinks.push({ id, status, reason: 'issue_mapping_missing' });
        continue;
      }
      if (!authOk) {
        missingPrLinks.push({ id, status, issue_number: Number(mapped.issue_number || 0), reason: 'auth_missing' });
        continue;
      }
      const issue = issueByNumber(policy, Number(mapped.issue_number || 0));
      if (!issue) {
        missingPrLinks.push({ id, status, issue_number: Number(mapped.issue_number || 0), reason: 'issue_not_found' });
        continue;
      }
      if (!hasPrLink(String(issue.body || ''), prLinkMarkers)) {
        missingPrLinks.push({ id, status, issue_number: issue.number, reason: 'pr_link_missing' });
      }
    }
  }

  const authFailure = policy.github.auth_required && !authOk;
  const prLinkStrict = policy.workflow && policy.workflow.require_pr_link_strict === true;
  const ok = !!reg.ok
    && !authFailure
    && duplicateIssueNumbers.length === 0
    && (!prLinkStrict || missingPrLinks.length === 0);

  const out = writeArtifactSet(
    { latestPath: policy.paths.latest_path, receiptsPath: policy.paths.receipts_path },
    {
      ok,
      type: 'backlog_github_sync',
      action: 'check',
      ts: nowIso(),
      strict,
      auth_ok: authOk,
      registry_ok: !!reg.ok,
      registry_error: reg.ok ? null : reg.error || 'registry_missing',
      mapped_count: Object.keys(stateRows).length,
      stale_mapping_count: staleMappings.length,
      stale_mappings: staleMappings.slice(0, 50),
      duplicate_issue_numbers: duplicateIssueNumbers,
      duplicate_issue_number_count: duplicateIssueNumbers.length,
      pr_link_strict: prLinkStrict,
      pr_link_missing_count: missingPrLinks.length,
      pr_link_missing: missingPrLinks.slice(0, 50),
      state_path: rel(policy.paths.state_path),
      registry_path: rel(policy.paths.registry_path),
      github: {
        host: policy.github.host,
        owner: policy.github.owner,
        repo: policy.github.repo
      }
    },
    { schemaId: 'backlog_github_sync_receipt', schemaVersion: '1.0', artifactType: 'receipt' }
  );

  emit(out, strict && !ok ? 2 : 0);
}

function statusCmd(policy: AnyObj) {
  const reg = loadRegistry(policy);
  const state = loadState(policy);
  const authOk = ghAuthOk(policy);
  const mapped = state && state.issues_by_id && typeof state.issues_by_id === 'object'
    ? Object.keys(state.issues_by_id).length
    : 0;

  emit({
    ok: true,
    type: 'backlog_github_sync',
    action: 'status',
    ts: nowIso(),
    auth_ok: authOk,
    enabled: policy.enabled,
    dry_run_default: policy.dry_run_default,
    strict_default: policy.strict_default,
    sync_statuses: policy.sync_statuses,
    registry_ok: !!reg.ok,
    registry_row_count: reg.ok ? Number(reg.row_count || 0) : 0,
    mapped_count: mapped,
    state_path: rel(policy.paths.state_path),
    latest_path: rel(policy.paths.latest_path),
    receipts_path: rel(policy.paths.receipts_path),
    github: {
      host: policy.github.host,
      owner: policy.github.owner,
      repo: policy.github.repo,
      project_sync: policy.github.project_sync === true
    }
  }, 0);
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  const cmd = String(args._[0] || 'status');
  if (args.help || cmd === '--help' || cmd === '-h' || cmd === 'help') {
    usage();
    process.exit(0);
  }

  const policy = loadPolicy(args.policy || DEFAULT_POLICY_PATH);
  if (!policy.enabled) {
    emit({ ok: true, type: 'backlog_github_sync', action: cmd, ts: nowIso(), skipped: 'disabled_by_policy' }, 0);
  }

  if (cmd === 'sync') return syncCmd(args, policy);
  if (cmd === 'check') return checkCmd(args, policy);
  if (cmd === 'status') return statusCmd(policy);

  usage();
  emit({ ok: false, error: `unknown_command:${cleanText(cmd, 80)}` }, 2);
}

main();
