// Layer ownership: core/layer2/ops (authoritative)
// SPDX-License-Identifier: Apache-2.0
use crate::deterministic_receipt_hash;
use serde_json::{json, Value};
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

const DEFAULT_POLICY_REL: &str = "client/runtime/config/observability_slo_runbook_closure_policy.json";
const DEFAULT_SLO_MAP_REL: &str = "config/autonomy_slo_runbook_map.json";
const DEFAULT_RUNBOOK_REL: &str = "docs/OPERATOR_RUNBOOK.md";
const DEFAULT_LATEST_REL: &str = "state/ops/observability_slo_runbook_closure/latest.json";
const DEFAULT_HISTORY_REL: &str = "state/ops/observability_slo_runbook_closure/history.jsonl";

fn print_json(value: &Value) { println!("{}", serde_json::to_string(value).unwrap_or_else(|_| "{\"ok\":false,\"error\":\"encode_failed\"}".to_string())); }
fn parse_flag(argv: &[String], key: &str) -> Option<String> { let pref = format!("--{key}="); let long = format!("--{key}"); let mut idx = 0usize; while idx < argv.len() { let token = argv[idx].trim(); if let Some(value) = token.strip_prefix(&pref) { return Some(value.to_string()); } if token == long && idx + 1 < argv.len() { return Some(argv[idx + 1].clone()); } idx += 1; } None }
fn now_iso() -> String { chrono::Utc::now().to_rfc3339_opts(chrono::SecondsFormat::Secs, true) }
fn clean_text(value: &str, max_len: usize) -> String { value.split_whitespace().collect::<Vec<_>>().join(" ").chars().take(max_len).collect() }
fn resolve_root(cli_root: &Path) -> PathBuf { env::var("OBS_SLO_RUNBOOK_CLOSURE_ROOT").ok().filter(|value| !value.trim().is_empty()).map(PathBuf::from).unwrap_or_else(|| cli_root.to_path_buf()) }
fn resolve_path(root: &Path, raw: Option<String>, fallback_rel: &str) -> PathBuf { match raw { Some(value) if !value.trim().is_empty() => { let path = PathBuf::from(value); if path.is_absolute() { path } else { root.join(path) } } _ => root.join(fallback_rel) } }
fn read_json(path: &Path) -> Option<Value> { fs::read_to_string(path).ok().and_then(|raw| serde_json::from_str::<Value>(&raw).ok()) }
fn write_json_atomic(path: &Path, value: &Value) -> Result<(), String> { if let Some(parent) = path.parent() { fs::create_dir_all(parent).map_err(|err| err.to_string())?; } let tmp = path.with_extension(format!("tmp-{}", std::process::id())); fs::write(&tmp, format!("{}\n", serde_json::to_string_pretty(value).map_err(|err| err.to_string())?)).map_err(|err| err.to_string())?; fs::rename(&tmp, path).map_err(|err| err.to_string())?; Ok(()) }
fn append_jsonl(path: &Path, value: &Value) -> Result<(), String> { if let Some(parent) = path.parent() { fs::create_dir_all(parent).map_err(|err| err.to_string())?; } use std::io::Write; let mut file = fs::OpenOptions::new().create(true).append(true).open(path).map_err(|err| err.to_string())?; let mut line = serde_json::to_string(value).map_err(|err| err.to_string())?; line.push('\n'); file.write_all(line.as_bytes()).map_err(|err| err.to_string()) }
fn rel(root: &Path, path: &Path) -> String { path.strip_prefix(root).unwrap_or(path).to_string_lossy().replace('\\', "/") }
fn load_policy(root: &Path, argv: &[String]) -> Value { let policy_path = resolve_path(root, parse_flag(argv, "policy").or_else(|| env::var("OBS_SLO_RUNBOOK_CLOSURE_POLICY_PATH").ok()), DEFAULT_POLICY_REL); let raw = read_json(&policy_path).unwrap_or_else(|| json!({})); let slo_map_path = raw.pointer("/inputs/slo_map_path").and_then(Value::as_str).map(ToString::to_string).unwrap_or_else(|| DEFAULT_SLO_MAP_REL.to_string()); let runbook_path = raw.pointer("/inputs/runbook_path").and_then(Value::as_str).map(ToString::to_string).unwrap_or_else(|| DEFAULT_RUNBOOK_REL.to_string()); let latest = raw.pointer("/outputs/latest_path").and_then(Value::as_str).map(ToString::to_string).unwrap_or_else(|| DEFAULT_LATEST_REL.to_string()); let history = raw.pointer("/outputs/history_path").and_then(Value::as_str).map(ToString::to_string).unwrap_or_else(|| DEFAULT_HISTORY_REL.to_string()); json!({ "version": raw.get("version").and_then(Value::as_str).unwrap_or("1.0"), "enabled": raw.get("enabled").and_then(Value::as_bool).unwrap_or(true), "inputs": { "slo_map_path": resolve_path(root, Some(slo_map_path), DEFAULT_SLO_MAP_REL), "runbook_path": resolve_path(root, Some(runbook_path), DEFAULT_RUNBOOK_REL) }, "outputs": { "latest_path": resolve_path(root, Some(latest), DEFAULT_LATEST_REL), "history_path": resolve_path(root, Some(history), DEFAULT_HISTORY_REL) }, "policy_path": policy_path }) }
fn cmd_run(root: &Path, argv: &[String]) -> Result<Value, String> { let policy = load_policy(root, argv); if !policy.get("enabled").and_then(Value::as_bool).unwrap_or(true) { let mut out = json!({"ok":true,"result":"disabled_by_policy","type":"observability_slo_runbook_closure_pass","authority":"core/layer2/ops"}); out["receipt_hash"] = Value::String(deterministic_receipt_hash(&out)); return Ok(out); } let slo_map_path = PathBuf::from(policy.pointer("/inputs/slo_map_path").and_then(Value::as_str).unwrap_or(DEFAULT_SLO_MAP_REL)); let runbook_path = PathBuf::from(policy.pointer("/inputs/runbook_path").and_then(Value::as_str).unwrap_or(DEFAULT_RUNBOOK_REL)); let map = read_json(&slo_map_path).unwrap_or_else(|| json!({})); let runbook = fs::read_to_string(&runbook_path).unwrap_or_default(); let mut blockers = Vec::new(); let entries = map.as_object().cloned().unwrap_or_default(); for (slo, hint_raw) in entries.iter() { let hint = clean_text(hint_raw.as_str().unwrap_or_default(), 240); if hint.is_empty() { blockers.push(json!({"gate":"slo_map","slo":slo,"reason":"missing_runbook_hint"})); continue; } if !runbook.contains(&hint) { blockers.push(json!({"gate":"runbook_coverage","slo":slo,"reason":"hint_missing_in_runbook","hint":hint})); } } let ts = now_iso(); let mut out = json!({"ok":blockers.is_empty(),"ts":ts,"type":"observability_slo_runbook_closure_pass","authority":"core/layer2/ops","checked_entries":entries.len(),"blockers":blockers,"policy_path":rel(root, Path::new(policy.get("policy_path").and_then(Value::as_str).unwrap_or_default()))}); out["receipt_hash"] = Value::String(deterministic_receipt_hash(&out)); let latest_path = PathBuf::from(policy.pointer("/outputs/latest_path").and_then(Value::as_str).unwrap_or(DEFAULT_LATEST_REL)); let history_path = PathBuf::from(policy.pointer("/outputs/history_path").and_then(Value::as_str).unwrap_or(DEFAULT_HISTORY_REL)); write_json_atomic(&latest_path, &out)?; append_jsonl(&history_path, &json!({"ts":out["ts"],"type":out["type"],"checked_entries":out["checked_entries"],"blocker_count":out["blockers"].as_array().map(|rows| rows.len()).unwrap_or(0),"ok":out["ok"]}))?; Ok(out) }
fn cmd_status(root: &Path, argv: &[String]) -> Value { let policy = load_policy(root, argv); let latest_path = PathBuf::from(policy.pointer("/outputs/latest_path").and_then(Value::as_str).unwrap_or(DEFAULT_LATEST_REL)); let mut out = json!({"ok":true,"ts":now_iso(),"type":"observability_slo_runbook_closure_pass_status","authority":"core/layer2/ops","latest":read_json(&latest_path),"policy_path":rel(root, Path::new(policy.get("policy_path").and_then(Value::as_str).unwrap_or_default()))}); out["receipt_hash"] = Value::String(deterministic_receipt_hash(&out)); out }
pub fn run(cli_root: &Path, argv: &[String]) -> i32 { let root = resolve_root(cli_root); let cmd = argv.first().map(|value| value.trim().to_ascii_lowercase()).unwrap_or_else(|| "status".to_string()); let result = match cmd.as_str() { "run" => cmd_run(&root, argv), "status" => Ok(cmd_status(&root, argv)), "help" | "--help" | "-h" => { println!("Usage:\n  protheus-ops observability-slo-runbook-closure run|status [--policy=<path>] [--strict=1|0]"); return 0; }, _ => Ok(json!({"ok":false,"error":format!("unknown_command:{cmd}")})), }; match result { Ok(payload) => { let exit = if payload.get("ok").and_then(Value::as_bool).unwrap_or(false) { 0 } else { 1 }; print_json(&payload); exit }, Err(err) => { print_json(&json!({"ok":false,"error":clean_text(&err,260)})); 1 } } }
